mo271/FormalBook

src/chapters/06_Every_finite_division_ring_is_a_field.lean
Definitions, statements of lemmas, main theorem and outlines for the proof.
=> Wedderburn (Ch. 6)

src/chapters/03_Binomial_coefficients_are_(almost)_never_powers.lean
updating 3. proof - filled in sorrys in first step
=> init binom never powers

src/chapters/03_Binomial_coefficients_are_(almost)_never_powers.lean
Regarding Lemmata:
alternative proof without induction still in progress
Regarding Step 1:
certain stuff outscourced as it is also needed for step 2
Regarding Step 2:
only sorrys left, some may be not trivial
Regarding Step 3:
working on how to express main hypothesis, most likely by a bijective funtion (work in Lemmata for 3)
Regarding Step 4:
cases for l=2 and l > 2 initialized
=> Major Update

leanpkg.toml, src/chapters/03_Binomial_coefficients_are_(almost)_never_powers.lean
in step 2 i wrote how to solve j < i and i < j given a hypothesis to be proved
commit message claiming it's step 3 is wrong
=> capter 3 (Binom); step 2; case i < j 

leanpkg.toml, src/chapters/03_Binomial_coefficients_are_(almost)_never_powers.lean
the way h_cases was formulated didnt shorten anything,
now its redone in a way, we only have to prove it for i < j and not for j < i as that follows trivially
=> chapter 3 , step 2, cases revisited

leanpkg.toml, src/chapters/03_Binomial_coefficients_are_(almost)_never_powers.lean
in the first claim there were i and j, however they are intended to refer to the same variable
tried to fix that
sorrys reguarding divisibility left (and still the inequalities)
=> cpater 3, step 2 

leanpkg.toml, src/chapters/03_Binomial_coefficients_are_(almost)_never_powers.lean
contradiction by inequalities, obtaining k³ > n (main work of step 4) still missing
=> chapter 3, step 4 

leanpkg.toml, src/chapters/03_Binomial_coefficients_are_(almost)_never_powers.lean
denoting some inequalities that will be needed
=> chapter 3 , step 4

leanpkg.toml, src/chapters/03_Binomial_coefficients_are_(almost)_never_powers.lean
any number to the lth power does not divide a
(needed among the steps)
finishing proof might be quite difficult
=> lemma notlthpowdiva

src/chapters/32_Lattice_paths_and_determinants.lean
issues marked with TODO
missing def: edge_set
=> Chapter 32 work

src/chapters/32_Lattice_paths_and_determinants.lean
new Def:
- loopless graphs
- trail path circuit cycle
- decomposition
- bypass
working on mapping
=> Major Update on Chapter 32

src/chapters/32_Lattice_paths_and_determinants.lean
contains all analogized objects from simple_graph.connectivity 
now work on weights, path system, path matrix
=> Chapter 32

src/chapters/32_Lattice_paths_and_determinants.lean
weights for edges and for walks are introduced
=> Update 32 (weights)

src/chapters/32_Lattice_paths_and_determinants.lean
Now a path system should be introducible. Hopefully.
=> Update Ch 32 (acyclic graph, subset of V with card n)

src/chapters/32_Lattice_paths_and_determinants.lean
acyclic graphs fixed
path system done
weights done
=> Update Ch 32

FormalBook/Ch06_Every_finite_division_ring_is_a_field.lean
This should change a few lines... please check!
=> Set-up for class number formula

FormalBook/Ch01_Six_proofs_of_the_infinity_of_primes.lean
@rwst finished the proof and cheanged the definition of `primeCountingReal` slighlty
=> Ch. 1: prove monotone_primeCountingReal

.github/workflows/blueprint.yml
=> Upgrade blueprint workflow

FormalBook/Chapter_27.lean, FormalBook/Chapter_28.lean, blueprint/lean_decls, blueprint/src/chapter/chapter28.tex
drive-by: moving it to the correct file
=> add latex for handshaking lemma

FormalBook/Chapter_45.lean
:tada: First theorem of the chapter.
I added a probability lemma that simplified the approach I initially took.
=> Done with Theorem 1
